Output bbs.webm

Set FontSize 11
Set Width 1200
Set Height 600

Sleep 1.5s
Type "cargo run --release"
Enter
Sleep 1.5s
Down
Sleep 1s
Up
Sleep 1s
Enter
Sleep 1s
Enter 2
Sleep 1.5s
Escape
Sleep 1s
Down
Sleep 1s
Enter
Sleep 500ms
Escape 2
Sleep 1s
Down
Enter 2
Sleep 1s
Escape 3
Sleep 1s
Down
Enter
Sleep 1s
Type "Hi"
Sleep 1s
Enter
Sleep 5s
Type "Sure..."
Enter
Sleep 2.5s
Type "Alright bots..."
Enter
Sleep 1s
Backspace
Escape
Sleep 500ms
Down
Enter
Sleep 1s

